### ISSUE TITLE
test paste

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/test#1]
![image](https://cloud.githubusercontent.com/assets/6943484/7536833/64d22dea-f561-11e4-9102-d9e6137982e7.png)

**Comment by tokkentakker** [comment]
![image](https://cloud.githubusercontent.com/assets/6943484/7536865/b49983f0-f561-11e4-8955-31559a9e6d01.png)

**Comment by tokkentakker** [comment]
![image](https://cloud.githubusercontent.com/assets/6943484/7536879/ceaf47f2-f561-11e4-93b3-c7c15cf349ee.png)

**Comment by tokkentakker** [comment]
mismatch on texel density unacceptable
![image](https://cloud.githubusercontent.com/assets/6943484/7536894/f8ecc418-f561-11e4-9c07-cb37a13a1969.png)

**Comment by egingric** [comment]
Uh, I'll get right on these fixes boss!

**Comment by tokkentakker** [comment]
You better


On May 8, 2015, at 8:15 PM, Eric D. Gingrich <notifications@github.com> wrote:

Uh, I'll get right on these fixes boss!
